const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router('db.json')
const middlewares = jsonServer.defaults()
const express = require('express')
server.use(express.static(__dirname+"/build"))
server.use(middlewares)
server.use(router)
server.listen(process.env.PORT||4000, () => {
  console.log('JSON Server is running')
})